# Generated by Django 3.1.5 on 2021-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
