# Generated by Django 3.1.5 on 2021-02-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='group_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='formcontent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
