# Generated by Django 3.1.5 on 2021-02-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('form', '0002_auto_20210201_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='group_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.group'),
        ),
    ]
