# Generated by Django 3.1.5 on 2021-02-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_master', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.group')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.branch')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('changes', models.BigIntegerField()),
                ('commit_time', models.BigIntegerField()),
                ('message', models.TextField()),
                ('branch_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.branch')),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('branch_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('column_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.column')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='repository_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.repository'),
        ),
    ]
